@echo off
echo Starting Hong Kong Weather Dashboard...
echo.
echo Installing dependencies...
call npm install
echo.
echo Running type check...
call npm run type-check
echo.
echo Starting development server...
call npm run dev
